{
 "title": "Wiregaurd_Monitor",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Latest Handshake",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "time() - wireguard_latest_handshake_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "wireguard_received_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Data Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "wireguard_transmitted_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}