FROM ubuntu:23.04

RUN apt-get update && apt-get install -y golang-go


RUN go version
WORKDIR /app

COPY ./wrieguard_setup.sh .

RUN chmod +x ./wrieguard_setup.sh && \
    ./wrieguard_setup.sh

COPY ./src .

