version: '3'

services:
  wg_service_2:
    image: wireguard_exporter_test
    container_name: wireguard_exporter_test
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./setup/wireguard/wg0_host_2.conf:/etc/wireguard/wg0.conf
    command: sh -c "wg-quick up wg0 && go test ./... -v"
    expose:
      - 9011

 

